# .github/workflows/caller.yml
name: Call Hello and Bye Workflows

on:
  workflow_dispatch:

jobs:
  call-hello:
    uses: srinathMandha/JavaActions/.github/workflows/hello.yml@main

  call-bye:
    uses: srinathMandha/JavaActions/.github/workflows/bye.yml@main

  log:
    needs: [call-hello, call-bye]
    runs-on: ubuntu-latest
    steps:
      - name: Log messages
        run: |
          echo "Hello output: ${{ needs.call-hello.outputs.message }}"
          echo "Bye output: ${{ needs.call-bye.outputs.message }}"
