name: Input Type Choice Example (Windows CMD with Parentheses)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment to deploy to"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  handle-choice:
    runs-on: windows-latest
    steps:
      - name: Set variables based on input
        shell: cmd
        run: |
          @echo off
          set "ENV=${{ github.event.inputs.environment }}"
          echo Selected environment: %ENV%
          
          if "%ENV%"=="development" (
              echo Setting environment to Development
              echo ENV_URL
