name: Admin Actions

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  check_admin_role:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check admin status
      run: |
        output=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
                     "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission")
        echo $output
        actor_role=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
                     "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission" \
                     | jq -r '.permission')
        
        if [ "$actor_role" == "admin" ]; then
          echo "User is an admin. Proceed with the workflow."
        else
          echo "User is not an admin. Exiting workflow."
          exit 1
        fi

    - name: Run actual tasks
      run: |
        # Put your tasks here that should only run for admins
